# -*- coding: utf-8 -*-
"""estudo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hW8illCmvPhCwrqRdB4hJHpqVUHPVrU9
"""

import pandas as pd

import matplotlib.pyplot as plt

"""## Começando pela limpeza de dados"""

df = pd.read_csv('/content/drive/MyDrive/Meus projetos pessoais/estudo - Página2.csv')

df.head()

df.info()

df.describe()

## Remover nulos

df['Quantidade'] = df['Quantidade'].fillna(1)

## Remover duplicados
df = df.drop_duplicates()

## Padronizar texto

df['produto'] = df['Produto'].str.lower().str.strip()

## Converter datas
df["data"] = pd.to_datetime(df["Data"], format="%d/%m/%Y")

"""## Análise dos dados"""

df.columns

# faturamento
df["faturamento"] = df["Preço"] * df["Quantidade"]

# total vendido
print("Faturamento total:", df["faturamento"].sum())

# produto mais vendido
print(df.groupby("Produto")["Quantidade"].sum())

# categoria mais lucrativa
print(df.groupby("Categoria")["faturamento"].sum())

"""# Gráfico"""

df.groupby("Produto")["faturamento"].sum().plot(kind="bar")
plt.title("Faturamento por Produto")
plt.show()

"""# Produtos de moda têm maior volume de vendas
O produto “tenis” é o mais vendido
Categoria moda tem ticket médio maior

## Análise mais profunda
"""

## Faturamento
df['faturamento'] = df['Preço'] * df['Quantidade']

df["Data"] = pd.to_datetime(df["Data"], dayfirst=True)

# mes e dia da semana
df['mes'] = df['Data'].dt.date
df['dia_semana'] = df['Data'].dt.day_name()

## Faturamento por mês
faturamento_mes = df.groupby('mes')['faturamento'].sum()
print(faturamento_mes)

## Produto mais vendido
produto_vendas = df.groupby('Produto')['Quantidade'].sum().sort_values(ascending=False)
print(produto_vendas)

## Categoria mais lucrativa
categoria_lucro = df.groupby('Categoria')['faturamento'].sum().sort_values(ascending=False)
print(categoria_lucro)

faturamento_mes.plot()
plt.title('Faturamento por mês')
plt.xlabel('Mês')
plt.ylabel('Faturamento')
plt.show()

"""**INSIGHTS**

👉 “O faturamento cresce em determinados meses, indicando possível sazonalidade.”

👉 “O produto X concentra a maior quantidade de vendas.”

👉 “Apesar de vender menos, a categoria Y gera mais receita.”
"""

## Analise por dias da semana
df.groupby('dia_semana')['faturamento'].sum().sort_values(ascending=False)

"""#### As vendas são mais fortes nas terças-feiras"""

## Salvar

import os

os.makedirs("data", exist_ok=True)

df.to_csv("data/vendas_tratado.csv", index=False)

df.to_csv("vendas_tratado.csv", index=False)

from google.colab import files
files.download("vendas_tratado.csv")